---

- name: "zones: Set signed zone files for DNSSEC"
  set_fact:
    bsd_named_zone_signed: ".signed"
  when: bsd_named_conf_dnssec_enable == "yes"

- name: "zones: Configure master zones in {{ bsd_named_conf_file }}"
  blockinfile:
    dest: "{{ bsd_named_conf_file }}"
    marker: "// {mark} ANSIBLE MANAGED BLOCK master {{ item.zone }}"
    insertafter: "EOF"
    owner: "root"
    group: "wheel"
    mode: "0644"
    validate: "named-checkconf %s"
    backup: "{{ bsd_named_backup_conf }}"
    block: |
      zone "{{ item.zone }}" {
              type {{ item.type }};
              key-directory "{{ bsd_named_conf_keys }}";
              allow-transfer  { {{ item.allow_transfer | join (';') }}; };
              update-policy local;
              auto-dnssec maintain;
              file "{{ bsd_named_conf_path }}/{{ item.type }}/{{ item.zone }}{{ bsd_named_zone_signed }}";
      };
  loop: "{{ bsd_named_conf_zone }}"
  when: item.type == "master"
  notify: restart named
  tags: bsd_dns_config_zone

- name: "zones: Configure slave zones in {{ bsd_named_conf_file }}"
  blockinfile:
    dest: "{{ bsd_named_conf_file }}"
    marker: "// {mark} ANSIBLE MANAGED BLOCK slave {{ item.zone }}"
    insertafter: "EOF"
    owner: "root"
    group: "wheel"
    mode: "0644"
    validate: "named-checkconf %s"
    backup: "{{ bsd_named_backup_conf }}"
    block: |
      zone "{{ item.zone }}" {
              type {{ item.type }};
              masters { {{ item.masters }} };
              allow-notify { {{ item.masters }} };
              key-directory "{{ bsd_named_conf_keys }}";
              auto-dnssec maintain;
              inline-signing yes;
              file "{{ bsd_named_conf_path }}/{{ item.type }}/{{ item.zone }}.bk";
      };
  loop: "{{ bsd_named_conf_zone }}"
  when: item.type == "slave"
  notify: restart named
  tags: bsd_dns_config_zone

- name: "zones: Configure master reverse zones in {{ bsd_named_conf_file }}"
  blockinfile:
    dest: "{{ bsd_named_conf_file }}"
    marker: "// {mark} ANSIBLE MANAGED BLOCK master {{ item.zone_in }}"
    insertafter: "EOF"
    owner: "root"
    group: "wheel"
    mode: "0644"
    validate: "named-checkconf %s"
    backup: "{{ bsd_named_backup_conf }}"
    block: |
      zone "{{ item.zone_in }}.IN-ADDR.ARPA" {
              type {{ item.type }};
              allow-transfer  { {{ item.allow_transfer }} };
              file "{{ bsd_named_conf_path }}/{{ item.type }}/{{ item.zone_in }}.IN-ADDR.ARPA";
      };
  loop: "{{ bsd_named_conf_zone }}"
  when: item.reverse == "yes" and item.type == "master"
  notify: restart named
  tags: bsd_dns_config_zone_in

- name: "zones: Configure slave reverse zones in {{ bsd_named_conf_file }}"
  blockinfile:
    dest: "{{ bsd_named_conf_file }}"
    marker: "// {mark} ANSIBLE MANAGED BLOCK slave {{ item.zone_in }}"
    insertafter: "EOF"
    owner: "root"
    group: "wheel"
    mode: "0644"
    validate: "named-checkconf %s"
    backup: "{{ bsd_named_backup_conf }}"
    block: |
      zone "{{ item.zone_in }}.IN-ADDR.ARPA" {
              type {{ item.type }};
              masters { {{ item.masters }} };
              file "{{ bsd_named_conf_path }}/{{ item.type }}/{{ item.zone_in }}.IN-ADDR.ARPA";
      };
  loop: "{{ bsd_named_conf_zone }}"
  when: item.reverse == "yes" and item.type == "slave"
  notify: restart named
  tags: bsd_dns_config_zone_in

- name: "zones: Create zone files"
  template:
    src: "zone.j2"
    dest: "{{ bsd_named_conf_path }}/{{ item.type }}/{{ item.zone }}"
    owner: "root"
    group: "wheel"
    mode: "0644"
    backup: "{{ bsd_named_backup_conf }}"
  register: bsd_named_zones_created
  loop: "{{ bsd_named_conf_zone }}"
  when: item.type == "master"
  notify: restart named
  tags: bsd_dns_config_zone

- name: "zones: Create reverse zone files"
  template:
    src: "zone-in.j2"
    dest: "{{ bsd_named_conf_path }}/{{ item.type }}/{{ item.zone_in }}.IN-ADDR.ARPA"
    owner: "root"
    group: "wheel"
    mode: "0644"
    backup: "{{ bsd_named_backup_conf }}"
  loop: "{{ bsd_named_conf_zone }}"
  when: item.reverse == "yes" and item.type == "master"
  notify: restart named
  tags: bsd_dns_config_zone_in

# EOF
...
