---
# handlers vbotka.freebsd-dns

- name: "enable and start named"
  service:
    name: "{{ bsd_named_service }}"
    state: started
    enabled: yes

- name: "disable and stop named"
  service:
    name: "{{ bsd_named_service }}"
    state: stopped
    enabled: no

- name: "start named"
  service:
    name: "{{ bsd_named_service }}"
    state: started

- name: "stop named"
  service:
    name: "{{ bsd_named_service }}"
    state: stopped

- name: "restart named"
  service:
    name: "{{ bsd_named_service }}"
    state: restarted
  when: bsd_named_enable

- name: "reload named"
  service:
    name: "{{ bsd_named_service }}"
    state: reloaded
  when: bsd_named_enable

- name: "create log"
  file:
    state: touch
    path: "{{ bsd_named_conf_log_file }}"
    mode: "0660"
    owner: "root"
    group: "bind"

#  shell: "touch {{bsd_named_conf_log_file}} && chmod 0660 {{bsd_named_conf_log_file}} && chown root:bind {{bsd_named_conf_log_file}}"
  
# TODO: ERROR! 'dict object' has no attribute 'zone'
#- name: sign zones
#  shell: "dnssec-signzone -o {{item.zone}} -k K{{item.zone}}.KSK /usr/local/etc/namedb/master/{{item.zone}} K{{item.zone}}.ZSK.key"
#  when: item.changed
#  with_items: bsd_named_zones_created.results
    
# EOF
...
